# Generated by Django 6.0.4 on 2026-04-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('risk_level', models.CharField(max_length=50)),
                ('high_factors', models.TextField(blank=True)),
                ('moderate_factors', models.TextField(blank=True)),
                ('is_pregnant', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
